on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master

    - uses: r-lib/actions/setup-r@master

    - uses: r-lib/actions/setup-pandoc@master

    - uses: actions/cache@v1
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Application Support/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    - name: Install Package Dependencies
      run: |-
        Rscript -e "install.packages('renv')"
        Rscript -e "renv::restore(confirm = FALSE)"

    - name: Install package
      run: R CMD INSTALL .

    - name: Deploy package
      run: |
        Rscript -e "pkgdown:::deploy_local(new_process = FALSE, remote_url = 'https://x-access-token:${{secrets.GITHUB_PAT}}@github.com/${{github.repository}}.git')"
